name: Test build push 
on:
  push:
    branches: [ main ]
jobs:
  test:
    name: "Test code and check lint"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Python Poetry Action
        uses: abatilo/actions-poetry@v2.1.0
      - name: Install dependencies
        run: |
          pip install tox
      - name: "tests"
        run: |
          tox
  build:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/python_cloud_project_template:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
